name: arboles_app
description: Proyecto de Programación III - Gestión de Árboles Binarios

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  package_info_plus: ^8.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Manejo de estado
  provider: ^6.1.2

  # Dibujos y conexiones visuales
  flutter_svg: ^2.0.10+1

  # Utilidades
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/